
server:
  port: 9000

logging:
  level:
    root: INFO

# logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

# jsp setting  // prefix (접두사 - 앞에 연결해주는 , suffix (접미사 - 뒤에 연결해주는) 의 값을 미리 셋팅해두면
#              // controller에서 return하여 링크를 호출할 때 전체 링크를 적지 않아도 된다! (코드 간결화)
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mariadb://localhost:3306/practice
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver

# MyBatis setting
mybatis:
  #sql file location
  mapper-locations: classpath:mapper/**/*.xml    #classpath = main 아래 resources 파일!
  type-aliases-package: com.spring.mvcproject
  configuration:
    map-underscore-to-camel-case: true   # 이름 규칙(camel-case만 맞춰주면 알아서 데이터를 넣어주겠다)
